### ISSUE TITLE
Warning: Text content did not match. Server

### ISSUE THREAD

**Issue by daviddang91** [postor/next-i18n-helper#8]
I'm getting the following warning on your browser console when I select the Chinese language, It error on server-side rendering.

`
react-dom.development.js?61bb:88 Warning: Text content did not match. Server: "我的博客" Client: "My Blog"
    in h1 (created by Index)
    in div (created by Index)
    in Index (created by withI18nextTranslation(Index))
    in withI18nextTranslation(Index) (created by Layout)
    in div (created by Layout)
    in Layout (created by Wrapper)
    in Wrapper (created by App)
    in App
    in ErrorBoundary (created by ReactDevOverlay)
    in ReactDevOverlay (created by Container)
    in Container (created by AppContainer)
    in AppContainer
    in Root
`

**Comment by postor** [comment]
it's because `i18next-xhr-backend` will restore text to untranslated before it load translation data from xhr, so the SSR go Chinese and inital react go without translation so the content won't match, when the xhr arrives the content go back to Chinese, cannot avoid it yet, if it really bothers you, you can fork and delay the  `i18next-xhr-backend`  initiation
